### ISSUE TITLE
Update WAF to allow the blocking of problematic IPs 

### ISSUE THREAD

**Issue by briri** [CDLUC3/dmptool#663]
We should update our WAF rules so that it allows for an IP black list.

See conversation in [this ticket](https://github.com/cdlib/cdlsys/issues/635)

**Comment by marisastrong** [comment]
I added a rule in Outlook for the dmptool@ucop.edu to manage the problem reported in https://github.com/cdlib/cdlsys/issues/635

<img width="833" alt="Screenshot 2024-11-20 at 2 25 03 PM" src="https://github.com/user-attachments/assets/d4d054f6-79fb-4f32-ab52-137a90b3867d">

**Comment by briri** [comment]
sample rule:
```
- Action:
    Block: {}
  Name: rate-limit
  Priority: ?
  Statement:
    RateBasedStatement:
      AggregateKeyType: IP
      Limit: ?
      ScopeDownStatement:
        RegexMatchStatement:
          FieldToMatch:
            UriPath: {}
          RegexString: (^\/contacts|^\/users/sign_in|^\/users/sign_up|^\//users/password/new|^\/$)
          TextTransformations:
          - Priority: 0
            Type: NONE
  VisibilityConfig:
    CloudWatchMetricsEnabled: true
    MetricName: rate-limit
    SampledRequestsEnabled: true
```
